import { GoogleGenerativeAI } from "@google/generative-ai";

/**
 * Initialize Gemini AI
 */
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

/**
 * Analyze PDF content unit-wise with AI
 */
export const analyzePDFContent = async (pdfText) => {
  if (!pdfText || pdfText.trim().length < 50) {
    throw new Error('PDF content is too short or could not be extracted. Please ensure the PDF is not a scan.');
  }

  try {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY is missing. Please add it to your environment variables.');
    }

    const model = genAI.getGenerativeModel({
      model: "gemini-1.5-flash",
      generationConfig: { responseMimeType: "application/json" }
    });

    const prompt = `You are an expert exam preparation AI tutor. Analyze the following educational content and provide a detailed unit-wise breakdown.
    
    Content:
    ${pdfText}
    
    Respond ONLY with a JSON object in this structure:
    {
      "units": [
        {
          "unitNumber": 1,
          "unitName": "Unit name",
          "importantTopics": [{"text": "Topic", "importance": "high", "reason": "Reason"}],
          "predictedQuestions": [{"question": "...", "marks": 2, "guidance": {"howToStart": "...", "keyPoints": [], "expectedLength": "...", "keywords": []}}],
          "studyGuidance": {"twoMark": {"expectedLines": "...", "keywords": []}, "fiveMark": {"expectedPoints": "...", "diagramNeeded": true, "explanation": "..."}, "tenMark": {"structure": "...", "minimumLength": "...", "mustInclude": []}}
        }
      ]
    }`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    return JSON.parse(text);
  } catch (error) {
    console.error('Gemini Analysis Error:', error);
    throw error;
  }
};

/**
 * Generate exam-ready answer for a question
 */
export const generateAnswer = async (question, marks, pdfContext, language = 'english') => {
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const languageInstruction = {
      english: 'Respond in English',
      tamil: 'Respond in Tamil',
      mixed: 'Respond in a mix of Tamil and English (Tanglish)',
    };

    const prompt = `Based on this context: ${pdfContext}
    Generate an exam-ready answer for: ${question} (${marks} marks).
    ${languageInstruction[language]}.
    Make it structured and clear. Use bullet points where appropriate.`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    return {
      question,
      marks,
      answer: text,
      language,
      source: 'Generated by Gemini AI',
    };
  } catch (error) {
    console.error('Gemini Answer Error:', error);
    throw error;
  }
};

/**
 * Generate voice assistant response
 */
export const generateVoiceResponse = async (userMessage, context, language = 'english') => {
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const prompt = `You are a friendly AI tutor. Context: ${context}
    User asked: ${userMessage}
    Provide a concise and helpful response.`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error('Gemini Voice Error:', error);
    throw error;
  }
};

/**
 * Conduct viva/oral test
 */
export const conductViva = async (topic, difficulty = 'medium', language = 'english') => {
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const prompt = `You are conducting an oral viva. Generate one concise question for the student.
    Topic: ${topic}, Difficulty: ${difficulty}, Language: ${language}`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error('Gemini Viva Error:', error);
    throw error;
  }
};

export default {
  analyzePDFContent,
  generateAnswer,
  generateVoiceResponse,
  conductViva,
};
