import OpenAI from 'openai';

// Initialize DeepSeek (OpenAI-compatible)
const openai = new OpenAI({
  apiKey: process.env.DEEPSEEK_API_KEY,
  baseURL: 'https://api.deepseek.com',
});

/**
 * Analyze PDF content unit-wise with AI
 */
export const analyzePDFContent = async (pdfText) => {
  if (!pdfText || pdfText.trim().length < 50) {
    throw new Error('PDF content is too short or could not be extracted. Please ensure the PDF is not a scan.');
  }

  try {
    if (!process.env.DEEPSEEK_API_KEY) {
      throw new Error('DEEPSEEK_API_KEY is missing. Please add it to your Render Environment Variables.');
    }

    const completion = await openai.chat.completions.create({
      messages: [
        {
          role: "system",
          content: "You are an expert exam preparation AI tutor. You analyze educational content and provide a detailed unit-wise breakdown in strict JSON format."
        },
        {
          role: "user",
          content: `Analyze this content and provide a unit-wise breakdown:
          
          ${pdfText}
          
          Respond ONLY with a JSON object in this structure:
          {
            "units": [
              {
                "unitNumber": 1,
                "unitName": "Unit name",
                "importantTopics": [{"text": "Topic", "importance": "high", "reason": "Reason"}],
                "predictedQuestions": [{"question": "...", "marks": 2, "guidance": {"howToStart": "...", "keyPoints": [], "expectedLength": "...", "keywords": []}}],
                "studyGuidance": {"twoMark": {"expectedLines": "...", "keywords": []}, "fiveMark": {"expectedPoints": "...", "diagramNeeded": true, "explanation": "..."}, "tenMark": {"structure": "...", "minimumLength": "...", "mustInclude": []}}
              }
            ]
          }`
        }
      ],
      model: "deepseek-chat",
      response_format: { type: "json_object" }
    });

    return JSON.parse(completion.choices[0].message.content);
  } catch (error) {
    console.error('DeepSeek Analysis Error:', error);
    if (error.message.includes('Insufficient Balance')) {
      throw new Error('DeepSeek API balance exhausted. Please top up your DeepSeek account.');
    }
    throw error;
  }
};

/**
 * Generate exam-ready answer for a question
 */
export const generateAnswer = async (question, marks, pdfContext, language = 'english') => {
  try {
    const languageInstruction = {
      english: 'Respond in English',
      tamil: 'Respond in Tamil',
      mixed: 'Respond in a mix of Tamil and English (Tanglish)',
    };

    const prompt = `Based on this context: ${pdfContext}
    Generate an exam-ready answer for: ${question} (${marks} marks).
    ${languageInstruction[language]}.
    Make it structured and clear.`;

    const completion = await openai.chat.completions.create({
      messages: [{ role: "user", content: prompt }],
      model: "deepseek-chat",
    });

    return {
      question,
      marks,
      answer: completion.choices[0].message.content,
      language,
      source: 'Generated by DeepSeek AI',
    };
  } catch (error) {
    console.error('DeepSeek Answer Error:', error);
    throw error;
  }
};

/**
 * Generate voice assistant response
 */
export const generateVoiceResponse = async (userMessage, context, language = 'english') => {
  try {
    const completion = await openai.chat.completions.create({
      messages: [
        { role: "system", content: `You are a friendly AI tutor. Context: ${context}` },
        { role: "user", content: userMessage }
      ],
      model: "deepseek-chat",
    });
    return completion.choices[0].message.content;
  } catch (error) {
    console.error('DeepSeek Voice Error:', error);
    throw error;
  }
};

/**
 * Conduct viva/oral test
 */
export const conductViva = async (topic, difficulty = 'medium', language = 'english') => {
  try {
    const completion = await openai.chat.completions.create({
      messages: [
        { role: "system", content: "You are conducting an oral viva. Generate one question." },
        { role: "user", content: `Topic: ${topic}, Difficulty: ${difficulty}, Language: ${language}` }
      ],
      model: "deepseek-chat",
    });
    return completion.choices[0].message.content;
  } catch (error) {
    console.error('DeepSeek Viva Error:', error);
    throw error;
  }
};

export default {
  analyzePDFContent,
  generateAnswer,
  generateVoiceResponse,
  conductViva,
};
